"""Models

Revision ID: 174de44ebf70
Revises: 
Create Date: 2022-01-29 21:55:55.169017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174de44ebf70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pills_id'), 'pills', ['id'], unique=False)
    op.create_index(op.f('ix_pills_name'), 'pills', ['name'], unique=True)
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specializations_id'), 'specializations', ['id'], unique=False)
    op.create_index(op.f('ix_specializations_title'), 'specializations', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=50), nullable=True),
    sa.Column('doctor_address', sa.String(length=250), nullable=True),
    sa.Column('doctor_phone', sa.String(length=50), nullable=True),
    sa.Column('specialization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_doctor_address'), 'doctors', ['doctor_address'], unique=False)
    op.create_index(op.f('ix_doctors_doctor_name'), 'doctors', ['doctor_name'], unique=False)
    op.create_index(op.f('ix_doctors_doctor_phone'), 'doctors', ['doctor_phone'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=50), nullable=True),
    sa.Column('patient_address', sa.String(length=250), nullable=True),
    sa.Column('patient_phone', sa.String(length=50), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_patient_address'), 'patient', ['patient_address'], unique=False)
    op.create_index(op.f('ix_patient_patient_name'), 'patient', ['patient_name'], unique=False)
    op.create_index(op.f('ix_patient_patient_phone'), 'patient', ['patient_phone'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days', sa.String(length=250), nullable=True),
    sa.Column('times', sa.String(length=100), nullable=True),
    sa.Column('pill_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['pill_id'], ['pills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_days'), 'recipes', ['days'], unique=False)
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_times'), 'recipes', ['times'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_times'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_days'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_patient_patient_phone'), table_name='patient')
    op.drop_index(op.f('ix_patient_patient_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_patient_address'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_doctors_doctor_phone'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_name'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_address'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_specializations_title'), table_name='specializations')
    op.drop_index(op.f('ix_specializations_id'), table_name='specializations')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_pills_name'), table_name='pills')
    op.drop_index(op.f('ix_pills_id'), table_name='pills')
    op.drop_table('pills')
    # ### end Alembic commands ###
