"""Medbase models new

Revision ID: a5d3c22ecd0f
Revises: 1d492c2e85b9
Create Date: 2022-01-28 11:53:11.159815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d3c22ecd0f'
down_revision = '1d492c2e85b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'doctors', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'patient', ['doctor_id'], ['id'])
    # ### end Alembic commands ###
